[theme]
# Primary accent color for interactive elements.
primaryColor = "#969696"

# Background color for the main content area.
backgroundColor = "#292929"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#171717"

# Color used for almost all text.
textColor = "#d9d9d9"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "monospace"

[server]
runOnSave = true

[client]
toolbarMode = "minimal"